title:            "Wenychan"
url:              http://wenyuchang.github.io/
permalink:        pretty
highlighter:      pygments
markdown:         kramdown
google_analytics: UA-21332781-7
timezone:         Asia/China
paginate: 5
paginate_path: "/blog/page:num"
gems:
  - jemoji
  - jekyll-mentions
